# sonarqube-values.yaml

# Enable the Community Build specifically
community:
  enabled: true

# sonarqube-values.yaml

tolerations:
  - key: "cloud.google.com/compute-class"
    operator: "Equal"
    value: "sonarqube-node-config"
    effect: "NoSchedule"

monitoringPasscode: "Aa12345678"

# Link to your existing StatefulSet database
jdbcOverwrite:
  enable: true
  jdbcUrl: "jdbc:postgresql://postgres-sonar-service:5432/sonar"
  jdbcUsername: "sonar"
  jdbcPassword: "sonar"

# GKE Autopilot Requirements
# Autopilot blocks root/privileged init containers by default.
initSysctl:
  enabled: false
initFs:
  enabled: false

sonarProperties:
  sonar.search.javaAdditionalOpts: "-Dnode.store.allow_mmap=false"
# Autopilot requires explicit resource requests
resources:
  requests:
    cpu: "2"
    memory: "8Gi"  # Increased from 4Gi to meet the 1:4 ratio
  limits:
    cpu: "2"
    memory: "8Gi"

# Persistence for Search Indices (Elasticsearch)
elasticsearch:
  persistence:
    enabled: true
    size: 5Gi

# Service configuration
service:
  type: ClusterIP # Use this for internal backend communication