community:
  enabled: true

# New required field for chart validation
monitoringPasscode: "Aa12345678" 

jdbcOverwrite: 
  enabled: true
  jdbcUrl: "jdbc:postgresql://postgres-sonar-service:5432/sonar"
  jdbcUsername: "sonar"
  jdbcPassword: "sonar"

postgresql:
  enabled: false 
  postgresqlServer: "postgres-sonar-service"
  postgresqlDatabase: "sonar"
  postgresqlUsername: "sonar"
  postgresqlPassword: "sonar"

# GKE Autopilot Requirements
initSysctl:
  enabled: false
initFs:
  enabled: false

sonarProperties:
  sonar.search.javaAdditionalOpts: "-Dnode.store.allow_mmap=false"

elasticsearch:
  persistence:
    enabled: true
    size: 5Gi

service:
  type: ClusterIP

# Add this to your sonarqube-values.yaml

livenessProbe:
  initialDelaySeconds: 120 # Give it 2 minutes before checking
  periodSeconds: 30
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 60  # Give it 1 minute before checking
  periodSeconds: 30
  failureThreshold: 6

# Also, let's bump the memory slightly to ensure Elasticsearch doesn't crash
resources:
  requests:
    cpu: "500m"
    memory: "3Gi" # 3Gi is safer for the 8.19.8 Elasticsearch engine
  limits:
    cpu: "500m"
    memory: "3Gi"