apiVersion: v1
kind: Service
metadata:
  name: postgres-sonar-service
  namespace: sonarqube
spec:
  selector:
    app: postgres-sonar
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}