apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: 6379
      protocol: TCP
      name: redis