apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployments/backend.yaml
  - deployments/frontend.yaml
  - stateful-state/postgres-state.yaml
  - stateful-state/redis-state.yaml
  - services/backend-service.yaml
  - services/frontend-service.yaml
  - services/redis-service.yaml
  - services/postgres-service.yaml
  - configmaps/application-config.yaml
  - configmaps/azure-devops-config.yaml
  - ingress.yaml

configMapGenerator:
  - name: common-config
    literals:
      - ENVIRONMENT=base
      - USE_MOCK_DATA=true

# Removed disableNameSuffixHash to allow for automatic Pod restarts on changes
secretGenerator:
  - name: all-secrets
    envs:
      - secrets/.env