apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployments/backend.yaml
  - deployments/frontend.yaml
  - deployments/redis.yaml
  - deployments/postgres.yaml
  - services/backend-service.yaml
  - services/frontend-service.yaml
  - services/redis-service.yaml
  - services/postgres-service.yaml
  - configmaps/application-config.yaml
  - ingress.yaml
  - secrets/postgres-secret.yaml
  - secrets/redis-secret.yaml
  - persistent-volume-claim/postgres-pvc.yaml

configMapGenerator:
  - name: common-config
    literals:
      - ENVIRONMENT=base
      - USE_MOCK_DATA=true
  - name: postgres-init-scripts
    files:
      # This points to the folder containing your .sql or .sh files
      - database-replace-later-helm/init/01-create-database.sql

# Removed disableNameSuffixHash to allow for automatic Pod restarts on changes
secretGenerator:
  - name: common-secrets
    envs:
      - secrets/.env