# charts/frontend/values.yaml
image:
  tag: latest

service:
  type: ClusterIP
  port: 3000
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

secretName: all-secrets

ingress:
  enabled: true
  className: openshift-default
  host: devops-hub.your-domain.example.com
  path: /
  tls: true
  annotations:
    route.openshift.io/termination: "edge"
    route.openshift.io/insecure-edge-termination-policy: "Allow"