# charts/frontend/values.yaml
image:
  tag: latest

service:
  type: ClusterIP
  port: 3000
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

secretName: all-secrets

ingress:
  enabled: true
  className: nginx
  host: devops.internal.company.prod
  path: /
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"