apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-control-center

resources:
  - ../../base/namespace.yaml
  - ../../base/deployments/api-gateway.yaml
  - ../../base/configmaps/application-config.yaml
  - ../../base/ingress.yaml

configMapGenerator:
  - name: dev-config
    literals:
      - ENVIRONMENT=development
      - USE_MOCK_DATA=true

replicas:
  - name: api-gateway
    count: 1
