apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-control-center-dev

resources:
  - ../../base

configMapGenerator:
  - name: dev-config
    literals:
      - ENVIRONMENT=development
      - USE_MOCK_DATA=true

# Use 'patches' as 'patchesStrategicMerge' is deprecated
patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml