apiVersion: v1
kind: Service
metadata:
  name: postgres-n8n-service
  namespace: n8n
spec:
  selector:
    app: postgres-n8n
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}