apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: {{ .Values.postgres.serviceName }}
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: {{ .Values.postgres.memoryLimit }}
              cpu: {{ .Values.postgres.cpuLimit }}
            limits:
              memory: {{ .Values.postgres.memoryLimit }}
              cpu: {{ .Values.postgres.cpuLimit }}
          env:
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.postgres.postgresUser }}
            - name: POSTGRESQL_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Values.postgres.secretName }}, key: POSTGRES_PASSWORD } }
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgres.postgresDB }}
            - name: POSTGRESQL_PORT_NUMBER
              value: {{ .Values.postgres.port | quote }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init-scripts
          configMap: { name: postgres-init-scripts }
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}