apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: {{ .Values.postgres.serviceName }}
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: {{ .Values.postgres.memoryLimit }}
              cpu: {{ .Values.postgres.cpuLimit }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.postgresUser }}
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Values.postgres.secretName }}, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              value: {{ .Values.postgres.postgresDB }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.serviceName }}
            # String interpolation for DATABASE_URL
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init-scripts
          configMap: { name: postgres-init-scripts }
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}