apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  {{- range $path, $bytes := .Files.Glob "database/*.sql" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}