apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: {{ .Values.redis.serviceName }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          resources:
            requests:
              cpu: "250m"    # 0.25 CPU
              memory: "512Mi" # 512 MB
            limits:
              cpu: "500m"
              memory: "1Gi"
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.redis.storageSize }}