apiVersion: v1
kind: Secret
metadata:
  name: all-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.global.secrets.postgresPassword | quote }}
  REDIS_PASSWORD: {{ .Values.global.secrets.redisPassword | quote }}
  # SESSION_SECRET: {{ .Values.global.secrets.sessionSecret | quote }}
  # JWT_SECRET: {{ .Values.global.secrets.jwtSecret | quote }}
  # SSO_CLIENT_SECRET: {{ .Values.global.secrets.ssoClientSecret | quote }}
  # AZURE_DEVOPS_PAT: {{ .Values.global.secrets.azureDevopsPat | quote }}
  # SONARQUBE_TOKEN: {{ .Values.global.secrets.sonarqubeToken | quote }}
  # ARTIFACTORY_API_KEY: {{ .Values.global.secrets.artifactoryApiKey | quote }}
  # SERVICENOW_PASSWORD: {{ .Values.global.secrets.serviceNowPassword | quote }}
  # AI_CHATBOT_TOKEN: {{ .Values.global.secrets.aiChatbotToken | quote }}
  # VAULT_TOKEN: {{ .Values.global.secrets.vaultToken | quote }}