apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:  
                secretKeyRef:
                  name: all-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_PORT
              valueFrom:  
                secretKeyRef:
                  name: all-secrets
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              value: postgres-service
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          volumeMounts:
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init-scripts
          configMap:
            name: postgres-init-scripts
  volumeClaimTemplates: # Automatically creates PVCs for each pod
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi