apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-devops-config
  labels:
    app: api-gateway
    component: azure-devops
data:
  # Azure DevOps REST API base URL
  # not used - need to delete from code 
  #api-url: "https://dev.azure.com"
  
  # Optional: Query user email for WIQL work item filters
  # Leave empty to use authenticated user's email
  AZURE_DEVOPS_QUERY_USER: "golden.mihel@gmail.com"

  # Organization name (used in URLs)
  # Example: https://dev.azure.com/{organization}
  AZURE_DEVOPS_ORGANIZATION: "DevCollection-Inheritance"
