apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  POSTGRES_HOST: {{ .Values.global.endpoints.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.global.endpoints.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.global.endpoints.postgresDB | quote }}
  DATABASE_URL: {{ .Values.global.endpoints.databaseUrl | quote }}
  POSTGRES_USER: {{ .Values.global.endpoints.postgresUser | quote }}
  REDIS_HOST: {{ .Values.global.endpoints.redisHost | quote }}
  REDIS_PORT: {{ .Values.global.endpoints.redisPort | quote }}
  LLM_BASE_URL: {{ .Values.global.llm.baseUrl | default "" | quote }}
  LLM_MODEL: {{ .Values.global.llm.model | default "gpt-4o-mini" | quote }}
