apiVersion: v1
kind: Secret
metadata:
  name: all-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | default "" | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | default "" | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | default "" | quote }}
  HUB_ADMIN_USERNAME: {{ .Values.secrets.hubAdminUsername | default "" | quote }}
  HUB_ADMIN_PASSWORD: {{ .Values.secrets.hubAdminPassword | default "" | quote }}
  AZURE_DEVOPS_BASE_URL: {{ .Values.secrets.azureDevopsBaseUrl | default "" | quote }}
  AZURE_DEVOPS_ADMIN_PAT: {{ .Values.secrets.azureDevopsAdminPat | default "" | quote }}
  SNOW_BASE_URL: {{ .Values.secrets.snowBaseUrl | default "" | quote }}
  SNOW_API_USERNAME: {{ .Values.secrets.snowApiUsername | default "" | quote }}
  SNOW_API_PASSWORD: {{ .Values.secrets.snowApiPassword | default "" | quote }}
  ARTIFACTORY_BASE_URL: {{ .Values.secrets.artifactoryBaseUrl | default "" | quote }}
  SONARQUBE_BASE_URL: {{ .Values.secrets.sonarqubeBaseUrl | default "" | quote }}
  CONFLUENCE_BASE_URL: {{ .Values.secrets.confluenceBaseUrl | default "" | quote }}