apiVersion: v1
kind: Secret
metadata:
  name: all-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | default "" | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | default "" | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | default "" | quote }}
  OAUTH_CLIENT_ID: {{ .Values.secrets.oauthClientId | default "" | quote }}
  OAUTH_CLIENT_SECRET: {{ .Values.secrets.oauthClientSecret | default "" | quote }}
  HUB_ADMIN_USERNAME: {{ .Values.secrets.hubAdminUsername | default "" | quote }}
  HUB_ADMIN_PASSWORD: {{ .Values.secrets.hubAdminPassword | default "" | quote }}
  AZURE_DEVOPS_PAT: {{ .Values.secrets.azureDevopsPat | default "" | quote }}
  AZURE_DEVOPS_ADMIN_PAT: {{ .Values.secrets.azureDevopsAdminPat | default "" | quote }}
  SERVICENOW_URL: {{ .Values.secrets.servicenowUrl | default "" | quote }}
  SERVICENOW_USERNAME: {{ .Values.secrets.servicenowUsername | default "" | quote }}
  SERVICENOW_PASSWORD: {{ .Values.secrets.servicenowPassword | default "" | quote }}