apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    tier: {{ .Values.tier | default "backend" }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      protocol: TCP
      name: http