name: CI - Frotend Service

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Docker image
        run: docker build -t frontend:latest ./frontend

      - name: Push Docker image
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker tag frontend:latest europe-west1-docker.pkg.dev/devops-idp-489012/devops-idp/frontend:latest
          docker push europe-west1-docker.pkg.dev/devops-idp-489012/devops-idp/frontend:latest