name: CI - frontend

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Currently don't need don't have tests
      # - name: Install dependencies
      #   run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: Build Docker image
        run: docker build -t frontend:latest ./frontend

      - name: Push Docker image
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth configure-docker LOCATION-docker.pkg.dev
          docker tag frontend:latest LOCATION-docker.pkg.dev/PROJECT/REPO/frontend:latest
          docker push LOCATION-docker.pkg.dev/PROJECT/REPO/frontend:latest