name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
  workflow_dispatch:

concurrency:
  group: service-frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    uses: ./.github/workflows/template-workflow.yml
    with:
      service_path: frontend
      image_name: frontend
      gcp_project: devops-idp-489012
      gcp_region: europe-west1
    secrets: inherit