name: Helm Chart Template

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      chart_name:
        required: true
        type: string
      gcp_project:
        required: true
        type: string
      gcp_region:
        required: true
        type: string
      repository_name: # The name of your Artifact Registry repo (e.g., 'devops-idp')
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.gcp_project }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to Artifact Registry
        run: |
          gcloud auth print-access-token | helm registry login -u oauth2accesstoken \
          --password-stdin https://${{ inputs.gcp_region }}-docker.pkg.dev

      - name: Lint, Package and Push
        run: |
          CHART_PATH="${{ inputs.chart_path }}"
          REGISTRY_URL="oci://${{ inputs.gcp_region }}-docker.pkg.dev/${{ inputs.gcp_project }}/${{ inputs.repository_name }}"
          
          echo "Linting chart at $CHART_PATH..."
          helm lint $CHART_PATH
          
          echo "Packaging chart..."
          # Package the chart and capture the output filename
          PACKAGE_OUTPUT=$(helm package $CHART_PATH)
          PACKAGE_FILE=$(echo "$PACKAGE_OUTPUT" | awk '{print $NF}')
          
          echo "Pushing $PACKAGE_FILE to $REGISTRY_URL..."
          helm push "$PACKAGE_FILE" "$REGISTRY_URL"